### ISSUE TITLE
How to install it on RG350

### ISSUE THREAD

**Issue by dbaldan** [Poligraf/openbor_retrofw_6391#1]
Hello there. I am O Ilusionista, you've commented on my channel about your RG350 port.
I am trying to install it but no success. Since I am very new to this, can you give me a step by step guide to do it?

Thanks

**Comment by Poligraf** [comment]
Omg , thank you for replying. I will send you a test version in the next 24 hours.

I have difficulty in debugging the rg350. It caused a blue colour shift when the resolution was 320x200. This did not happen on the retrofw. As I do not have a 350 device bug testing this was slow.

If you are happy to be spammed, I am happy to keep sending you test builds here. Is that ok?

**Comment by dbaldan** [comment]
Oh really thanks!
And you can keep send me the test versions for sure :)

**Comment by Poligraf** [comment]
I had a couple of issues which will be painful to fix if I backport 6330. 

This has mostly to do with backporting SDL2 to SDL1. 

I have to use SDL1 because retrofw devices only support SDL1. RG350 does support SDL2. I am a bit hesitant when I started porting SDL2 as I need to compile sdl2_gfx statically and there is no way for me to test if I am doing the right thing without having the physical device.

I went through all the notes on http://www.chronocrash.com/forum/index.php?PHPSESSID=eo9td44kqnfjqga38gtpj4jhu7&board=25.0 and I can not see major differences between 6330 and 6391, so I would like to continue attempting to do 6391 and get that one right for both retrofw and rg350 and using sdl1 to keep my sanity.

Disclaimer I am not a porting ninja, but someone who appreciates your work, I am a hospital pharmacist :D

PPS SDL1 will not work with games with a larger resolution than 800x600. So He-Man crashes.

Grab from here and PAKs go to `/media/data/local/home/games/openbor/Paks/`
https://github.com/Poligraf/openbor_retrofw_6391/releases/download/1_alpha/OpenBOR.opk

**Comment by dbaldan** [comment]
Thanks for your effort. Version 6391 has an issue of wrong effects appearing when a move hit, which ruins the game experience.

But I will test it asap and report.

Thanks!

**Comment by Poligraf** [comment]
Ok i will work on sdl2 version for 6330. I  didnt know of the bug, but you are the expert

**Comment by dbaldan** [comment]
I am testing the game. The bug u mentioned isn't happening :) 

The port works fine, but maybe my game is too heavy for the console, as I have some slowdown.

Maybe ita thanks to the fact the screen is forced to shrink fr 16:9 resolution to a 4:3 (I think they had changed it on the past) as the older version does not do that. 

I noticed the preview images has wrong colors, I think it's related to a change they made to fix the Wii port. I will try to gather more people to help
![IMG_20201024_094535776](https://user-images.githubusercontent.com/31666009/97082146-ea6e8780-15dd-11eb-9ab8-2b8456dcd0f8.jpg)

Thanks for your hard work

**Comment by Poligraf** [comment]
For slowness
This means you need sdl2. The game is definetely not heavy for the rg350. I hoped it will be better on that defvce as it is faster. On retrofw there is slowdown.

For color change this is a bug which i have not figured out, it does not happen on retrofw. It affects start menu and older games.

**Comment by dbaldan** [comment]
Ah I see. 

Do you think is there a way to change how the fullscreen looks? I noticed there are some missing video options under OPTIONS, take a look.

https://i.imgur.com/hUV9vW5.png

If one of the modes (either full or window) could display the game without shrinking it down - even if it cuts part of the image, it would be perfect, so the user can choose which version he wants to.
This is a video of a friend of mine (put it at 14:16) and you will see what I am talking about https://www.youtube.com/watch?v=73yMpjM9RAc - that is how it worked on the past.

Anyway, thanks for your work until now :)

**Comment by Poligraf** [comment]
Fileters disabled in code as it was making the game even slower.

I am not sure  if the rg350 has enough horse power to run them without sdl2 to be honest. Sdl2 is the way to go.

Your friends video uses the legacy code for all of the dingoo devices, which says to only display the first 320x240 pixels. This works great for 99% of games but you loose your health bar in avengers. You cant get the cropped window to display health for you and enemies due to tue resolution you are using

The code which produces that cutting of the screen is found in `openbor.c`

`#if OPENDINGUX || GP2X
    videoMode = 0;
#endif `

**Comment by Poligraf** [comment]
The path forward as follows

Leave 6391 for retrofw using sdl1
6330 using sdl2 for rg350.

**Comment by Poligraf** [comment]
Moving the work on 6330 with `sdl2` a new repository. Check that one out.
https://github.com/Poligraf/openbor_6330_rg350

opk is under that repository
https://github.com/Poligraf/openbor_6330_rg350/releases/download/1/OpenBOR.opk
